### PR TITLE
Issue 1/add google finance download

### PR DESCRIPTION
**Pull request by bizcad**
Probably the easiest way to review the changes is to go to my <a href ="https://github.com/QuantConnect/ToolBox.git">repo</a> and clone it into a project on your machine.
 You can then run the 
tests to see that the QuantConnect.GoogleFinance is able to save files.  By debugging into the UI you can trace through the buttons and checkboxes.  Also read the docx or pdf file in the Documentation folder.

This repo is commited as debug code.  The test all work on my machine ;o).  I think I have all the paths generic enough.  The default save directory is in the app.config file and is set to the Tests/debug/bin folder for my machine. 

&lt;add key="defaultOutputDirectoryPath" value="C:\Users\Nick\Documents\Visual Studio 2013\Projects\ToolBox\Tests\bin\Debug\"/&gt;

The UI should give you a dialog on where to get lists of securities and the folder to which to save the downloaded data.

Nick

### CODE REVIEW

**Comment by jaredbroad** [comment]
Very intense code base @bizcad! Would you consider collapsing it into a console app? You might want to review the existing CLI (very simple) application for QuantQuote data. 

The other app is command line only where the user enters the directories etc as part of the inputs. Then once all inputs are done it starts processing.

The project "MarketData\MarketData.csproj" seems to be missing from your repo and the pull request. It seem like the key part to make it all work.

**Comment by bizcad** [comment]
Shucks.  MarketData.csproj should not be a part of the repo.  That is the name of my development project.  

The 6 errors I get after commiting AllDataDownloaderTests are because I am not using NUnit, but  Microsoft.VisualStudio.TestTools.UnitTesting; for the test runner.  Apparently travis does not like that.  Do I need to trans code to NUnit?

I did review the QuantQuote cli and I can indeed collapse the tester into a command line.  Maybe something like this:

<pre>
Console.WriteLine(" Console.WriteLine("1. Source of symbol list : ");
                symbolListFile= (Console.ReadLine() ?? "");                
Console.WriteLine(" Console.WriteLine("2. Destination LEAN Data directory: ");
                destinationDirectory = (Console.ReadLine() ?? "");      
Console.WriteLine("3. Enter Resolution (daily, minute): ");
                resolution = (Console.ReadLine() ?? "");          
</pre>

GoogleFinance does not support resolution smaller than minute.  

The Source Directory is not needed as the data is downloaded from GoogleFinance.  A list of symbols is good and the list is read from a csv file with the ticker in column 1 and the Exchange in column 2.  Other columns in the csv file are ignored.  Of course the symbol list could be read in from the console.

**Comment by bizcad** [comment]
Which version of NUnit test framework is travis expecting?

**Comment by bizcad** [comment]
I do not mean to be bother, but what are the merge conflicts that must be resolved?

Nick

**Comment by mchandschuh** [comment]
Hey @bizcad! No need to close this!  I'm not sure what the merge issues are, typically all it means is you need to merge origin/master into the branch.

**Comment by bizcad** [comment]
@mchandschuh It is not the merge issues.  

I have been corresponding with Jared.  He wants a simpler solution and feels that this work is too complex.  I deleted it and will reopen when I have a simpler solution more in line with what he wants.

**Pull request closed without merging**
